# Generated by Django 5.0.4 on 2024-05-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="deleted_date",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="last_modified",
        ),
    ]
