# Generated by Django 5.0.4 on 2024-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transaction_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
